# Generated by Django 4.1.1 on 2022-10-07 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webScraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='users',
        ),
        migrations.AddField(
            model_name='internship',
            name='favorite',
            field=models.ManyToManyField(blank=None, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
