# Generated by Django 4.1.1 on 2022-10-07 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webScraping', '0002_remove_internship_users_internship_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='favorite',
        ),
        migrations.AddField(
            model_name='internship',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
